# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 21

Metrics/LineLength:
  Max: 147

Metrics/MethodLength:
  Max: 15
