plugin:
    type: docker
    managed: true # Docker only setting
    config:
        repo: username/plugin # Required
        tag: latest # Latest used by default, can override
        ports: # SLAPI will assign routing port, any external ports for monitoring services will need to be identified.
        command: # If a custom command is required at plugin start
        env: # List of environment variables
            - API=1u3042034
            - SERVICE=123490ijkd

plugin2:
    type: url # SLAPI compatible endpoint (lambda or other service)
        config:
            url: https://whatever.com/mypluginapi/v1/
            # basic auth example
            auth:
                username: user
                password: all the secrets
            # token auth example
            token: 23u4902iurajsdfa834
