swagger: "2.0"
info:
  version: 1.0.0
  title: SLAPI Bot
  description: Simple Lightweight API Bot Framework
  contact:
    name: SLAPI Team
    url: https://github.com/ImperialLabs
  license:
    name: MIT
    url: https://github.com/ImperialLabs/slapi/blob/master/LICENSE
host: "localhost:8100"
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /speak:
    post:
      summary: Post in chatroom
      operationId: postMessage
      parameters:
        - name: message
          in: body
          description: message to post
          required: true
          schema:
            $ref: '#/definitions/framework'
      tags:
        - chat
      responses:
        "200":
          description: message response
          schema:
            type: array
            items:
              $ref: '#/definitions/framework'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
  /emote:
    post:
      summary: Emote in chatroom
      operationId: emoteMessage
      parameters:
        - name: message
          in: body
          description: message to post
          required: true
          schema:
            $ref: '#/definitions/framework'
      tags:
        - chat
      responses:
        "200":
          description: message response
          schema:
            type: array
            items:
              $ref: '#/definitions/framework'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
  /formatted:
    post:
      summary: Post in basic formatted text "*bold* `code` _italic_ ~strike~"
      operationId: formatMessage
      parameters:
        - name: message
          in: body
          description: message to post
          required: true
          schema:
            $ref: '#/definitions/framework'
      tags:
        - chat
      responses:
        "200":
          description: message response
          schema:
            type: array
            items:
              $ref: '#/definitions/framework'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
  /attachment:
    post:
      summary: "Post advanced messages, see https://api.slack.com/docs/message-attachments for more info"
      operationId: attachMessage
      parameters:
        - name: message
          in: body
          description: message to post
          required: true
          schema:
            $ref: '#/definitions/framework_attachment'
      tags:
        - chat
      responses:
        "200":
          description: message response
          schema:
            type: array
            items:
              $ref: '#/definitions/framework_attachment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'

definitions:
  framework:
    required:
      - message
      - room
    properties:
      message:
        type: string
      room:
        type: string
  framework_attachment:
    required:
      - text
    properties:
      text:
        type: string 
      title:
        type: string
      pretext:
        type: string
      mrkdwn_in:
        type: string
  error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
