FROM slapi/ruby:latest

# If label is named description it will set tier 1 or plugin description in chat help
LABEL "description"="Plugin Description"
# Use Labels for Help info, a help list will be compiled from the labels
LABEL "ARGNAME01"="Arg Description"
LABEL "ARGNAME02"="Arg Description"
LABEL "ARGNAME03"="Arg Description"
