FROM slapi/ruby:latest

# Use Labels for Help info, a help list will be compiled from the labels
LABEL "ARGNAME01"="Arg Description"
LABEL "ARGNAME02"="Arg Description"
LABEL "ARGNAME03"="Arg Description"

